name: go
on:
  pull_request:
  push:
jobs:
  build-and-test:
    env:
      GO111MODULE: 'on'
    strategy:
      fail-fast: true
      matrix:
        go: ['1.21.5']
        os:
        - ubuntu-latest
        - windows-latest
        - macos-latest
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    name: ${{ matrix.go }} on ${{ matrix.os }}
    steps:
    - run: go test ./... -coverprofile=coverage.txt -covermode=atomic

